name: Scrape Dolar api

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: '59/60 * * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - run: |
          npm run scrapper
          git config user.name Dolar-api-bot
          git config user.email IamBot@bot.com 
          git add .
          git commit -m "[bot] Update Dolar api Database"
          git diff --quiet && git push origin master
          
          
          
          
          
          
          
          
          
          
