name: Deploy API

on:
  push:
    branches:
      - master

jobs:
  deploy:
    #needs: test
    runs-on: ubuntu-22.04
    name: Deploy API to Cloudflare Workers
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true 
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: api
